AllCops:
  NewCops: enable
  Exclude:
    - "bin/console"

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/LineLength:
  Exclude:
    - "authorize_that.gemspec"
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Style/ClassAndModuleChildren:
  Exclude:
    - "test/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
